
#+TITLE: Optical Character Recognition
#+AUTHOR: Alexander Neville

This is my A-level course work project. I will be making a program which can convert hand written characters into digital ones. This program will also be able to identify where text is within a website.

* Contents :TOC:
- [[#computer-vision][Computer Vision]]
- [[#neural-network][Neural Network]]
  - [[#output-encoding][Output encoding]]

* Computer Vision

I would like to be able to find characters within an image so that I can pass each character to my recognition algorithm. This is a type of image segmentation problem: I need to split the image to find where a character is.

* Neural Network

I have established that a neural network is a good solution to the recognition problem. It will be able to classify the input image by activating an output neuron, which is interpretted by the program to determine the digital character to use.

** Output encoding

I would like to distinguish between all alphanumeric characters (36 outputs), although I can easily train more than one model. The network could have 36 output neurons, although I could create a more complex encoding standard that the program can interpret. This would reduce the number of output neurons.
